repos:
- hooks:
  - id: end-of-file-fixer
  - id: check-yaml
    args: ['--unsafe']  # Allow Python tags for mkdocs.yml
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: check-json
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
