site_name: python-cqrs
site_url: https://vadikko2.github.io/python-cqrs-mkdocs/
repo_url: https://github.com/vadikko2/python-cqrs
repo_name: vadikko2/python-cqrs
dev_addr: 127.0.0.1:8000
nav:
  - Home: index.md
  - Core Concepts:
    - Bootstrap:
      - Overview: bootstrap/index.md
      - Request Mediator: bootstrap/request_mediator.md
      - Streaming Mediator: bootstrap/streaming_mediator.md
      - Event Mediator: bootstrap/event_mediator.md
      - Message Brokers: bootstrap/message_brokers.md
      - Middlewares: bootstrap/middlewares.md
      - DI Containers: bootstrap/di_containers.md
      - Advanced: bootstrap/advanced.md
    - Dependency Injection: di.md
    - Commands / Requests Handling: request_handler.md
    - Stream Handling:
      - Overview: stream_handling/index.md
      - Configuration: stream_handling/configuration.md
      - FastAPI Integration: stream_handling/fastapi_integration.md
      - Reference: stream_handling/reference.md
    - Chain of Responsibility:
      - Overview: chain_of_responsibility/index.md
      - Examples: chain_of_responsibility/examples.md
      - Advanced: chain_of_responsibility/advanced.md
    - Events Handling:
      - Overview: event_handler/index.md
      - Event Flow: event_handler/event_flow.md
      - Runtime Processing: event_handler/runtime_processing.md
      - Parallel Processing: event_handler/parallel_processing.md
      - Event Types: event_handler/event_types.md
      - Examples: event_handler/examples.md
      - Best Practices: event_handler/best_practices.md
    - Transaction Outbox:
      - Overview: outbox/index.md
      - Implementation: outbox/implementation.md
      - Usage: outbox/usage.md
      - Examples: outbox/examples.md
      - Best Practices: outbox/best_practices.md
  - Integrations:
    - FastAPI Integration: fastapi.md
    - FastStream Integration: faststream.md
    - Event Producing: event_producing.md
    - Protobuf Integration: protobuf.md
theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate
    - content.code.select
  icon:
    annotation: material/plus-circle
  font:
    text: Roboto Mono
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - codehilite:
      guess_lang: false
  - admonition
  - pymdownx.blocks.caption # Images
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - attr_list
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/vadikko2/python-cqrs
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/python-cqrs/
plugins:
  - search
  - awesome-pages
  - autorefs
use_directory_urls: true
strict: true
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/navigation.js
